### ISSUE TITLE
Improve integration test coverage

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#1173]
We need to improve integration test coverage, even more important know with CoreCLR introducing allot of changes to get as much confidence as possible before v0.16.0 release.

#### Currently decent coverage is provided for:
- [x] Cake.Core.Tooling.ToolLocator
- [x] Cake.Common.ArgumentAliases
- [x] Cake.Common.EnvironmentAliases
- [x] Cake.Common.DirectoryAliases
- [x] Cake.Common.FileAliases - #1174
- [x] Cake.Common.Solution.SolutionAliases - #1185 
- [x] Cake.Common.Solution.Project.ProjectAliases - #1185
- [x] Cake.Common.Solution.Project.Properties.AssemblyInfoAliases - #1185
- [x] Cake.Common.Solution.Project.XmlDoc.XmlDocAliases - #1185
- [x] Cake.Common.ReleaseNotesAliases - #1190
- [x] Cake.Common.IO.ZipAliases - #1191 
- [x] Cake.Common.Text.TextTransformationAliases- #1194

#### PR Submitted
- [x] Cake.Common.Security.SecurityAliases - #1192
- [x] Cake.Common.Diagnostics.LoggingAliases - #1193
- [x] Cake.Common.Tools.Cake.CakeAliases - #1195
- [x] Cake.Common.Tools.DotNetCore.DotNetCoreAliases - #1197

**Comment by patriksvensson** [comment]
@devlead Should this issue be closed now or are there more planned integration tests?

**Comment by gep13** [comment]
@patriksvensson I think we should probably keep this issue open.  I suspect we might need a task list similar to what we had for adding documentation to aliases, to track which areas we want to add integration tests for.

**Comment by patriksvensson** [comment]
@gep13 Ok, should we simply move this to 0.17.0 then?

**Comment by gep13** [comment]
@patriksvensson not sure if that is right or not.  It would be good to increase the number of integration tests that we have, and this 0.16.0 seems like a good time to do it, as it is the largest change that we have had in a long time.

**Comment by patriksvensson** [comment]
@gep13 Yeah, agree. We should try to decide what kind of tests we need and what's missing.

**Comment by gep13** [comment]
@devlead what were your thoughts on which areas need to be hit?  During our call, it sounded like you had an idea about which areas need to be included?  If so, would it be possible to extend the list of sections that need to be looked at in the first post above, and then we can start knocking them off one by one?

**Comment by devlead** [comment]
@cake-build/team updated this issue to reflect current status, submitted 4 new PRs today.
So now only .NET Core aliases left on the plan, after that's merged this issue can be closed and will increase integration test coverage allot and have more confidence going forward with the v0.16.0 release.

**Comment by gep13** [comment]
@devlead are we good to close this?

**Comment by devlead** [comment]
@gep13 yes, we can add more coverage as needed next milestone.
