### ISSUE TITLE
Checklist for 1.0

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2776]
### Website

- [x] Documentation is out of date and needs to be updated.
- [x] Bootstrapper story needs to be documented, what do we recommend?
- [ ] Debugging (https://github.com/cake-build/website/issues/83)
- [x] Intellisense (https://github.com/cake-build/website/issues/493)
- [x] Frosting
- [ ] GitHub Actions (https://github.com/cake-build/website/issues/1036)

### Cake

- [ ] [Cake 1.0.0 Milestone](https://github.com/cake-build/cake/milestone/55)
- [ ] Remove unnecessary documentation and replace it with `<inheritdoc />` (https://github.com/cake-build/cake/issues/2894)
- [ ] Custom contexts (such as `DotCoverContext`) should inherit from `CakeContextAdapter` (https://github.com/cake-build/cake/issues/2895)
- [ ] Add tests for:
  - [ ] ContinuaProvider (https://github.com/cake-build/cake/issues/2896)
  - [ ] MyGetProvider (https://github.com/cake-build/cake/issues/2897)

### Cake VSCode Extension

- [ ] [Cake VSCode 1.0.0 Milestone](https://github.com/cake-build/cake-vscode/milestone/17)

### Frosting

- [x] Update README
- [x] Get it in a supportable shape
- [x] Update Cake release process to include Frosting release or merge code bases (https://github.com/cake-build/cake/issues/2874)
- [ ] [Cake.Frosting 1.0.0 Milestone](https://github.com/cake-build/frosting/milestone/6)

### Docker Image

- [ ] Update Cake release process to include Docker image update or merge code bases (https://github.com/cake-build/docker/issues/19)
- [ ] [Cake Docker 1.0.0 Milestone](https://github.com/cake-build/docker/milestone/1)

**Comment by pascalberger** [comment]
Add Frosting as possible option to run Cake scripts with https://github.com/cake-build/website/pull/977

**Comment by pascalberger** [comment]
Has been replace with https://github.com/orgs/cake-build/projects/2
